CREATE USER 'locpan'@'localhost' IDENTIFIED VIA mysql_native_password USING 'locpan';
GRANT ALL PRIVILEGES ON *.* TO 'locpan'@'localhost' REQUIRE NONE WITH GRANT OPTION MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
CREATE DATABASE IF NOT EXISTS `locpan`;GRANT ALL PRIVILEGES ON `locpan`.* TO 'locpan'@'localhost';

CREATE TABLE `locpan`.`sites` (`name` TINYTEXT NULL DEFAULT NULL , `ip` TINYTEXT NULL DEFAULT NULL , `dom` TINYTEXT NULL DEFAULT NULL , `hidden` BOOLEAN DEFAULT FALSE) ENGINE = InnoDB;